export const projects = [
  {
    id: "agent-pipeline",
    image: "/projects/agent-pipeline.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of coordinated retrieval, planning, tools, and verification agents.",
    title: "Multi-agent pipeline",
    subtitle: "Agents with a plan. And a fallback.",
    stack: "Python · LangGraph · Structured outputs",
    description:
      "A state-driven workflow for retrieval, planning, tool selection, static analysis, and verification.",
    points: [
      "Explicit error states and retries.",
      "Human-in-the-loop checkpoints.",
      "Structured output validation.",
    ],
  },
  {
    id: "rag-platform",
    image: "/projects/rag-platform.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of documents being matched through vector and keyword retrieval.",
    title: "RAG platform",
    subtitle: "Knowledge, within reach.",
    stack: "PGVector · BM25 · Cohere · Python",
    description:
      "An end-to-end retrieval platform combining vector similarity, lexical search, and reranking.",
    points: [
      "Tuned chunking and embeddings.",
      "Hybrid BM25 + embedding search.",
      "Cohere reranking and metadata routing.",
    ],
  },
  {
    id: "model-evals",
    image: "/projects/model-evals.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of comparing model outputs through an evaluation lens.",
    title: "Fine-tuning & evals",
    subtitle: "Better models. Measured.",
    stack: "Python · OpenAI · Gemini · Evals",
    description:
      "Domain-specific classification and summarization, paired with model evaluation.",
    points: [
      "Supervised fine-tuning.",
      "Accuracy and hallucination comparisons.",
      "Cost trade-offs across models.",
    ],
  },
  {
    id: "analysis-agent",
    image: "/projects/analysis-agent.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of code review with performance and compatibility checkpoints.",
    title: "Static analysis agent",
    subtitle: "A second set of engineering eyes.",
    stack: "LLM agents · API contracts · Static analysis",
    description:
      "An engineering review agent for performance, concurrency, and compatibility risks.",
    points: [
      "N+1 queries and caching inefficiencies.",
      "Schema drift and unsafe API contracts.",
      "Missing idempotency and concurrency risks.",
    ],
  },
  {
    id: "pricing-engine",
    image: "/projects/pricing-engine.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of pricing inference, caching, and request processing.",
    title: "ML pricing engine",
    subtitle: "Real-time decisions, at scale.",
    stack: "Python · Redis · DynamoDB · Autoscaling",
    description:
      "A high-throughput pricing system processing 500,000+ requests each day.",
    points: [
      "Python-based ML inference.",
      "Redis caching and DynamoDB state.",
      "Autoscaling for changing demand.",
    ],
  },
  {
    id: "project-memory",
    image: "/projects/project-memory.svg",
    imageLabel: "Concept illustration · Planned",
    imageAlt: "Concept artwork for the planned Project Memory application.",
    title: "Project Memory",
    subtitle: "Decisions, with a history.",
    stack: "Python · Graphiti · Graph database",
    description:
      "A planned application for exploring how project decisions change over time, built on Graphiti’s temporal knowledge graph.",
    points: [
      "Ingest project documents and meeting notes.",
      "Explore decisions through a timeline and relationship graph.",
      "Compare historical answers with their supporting evidence.",
    ],
    status: "planned",
    upstream: "Graphiti",
    upstreamUrl: "https://github.com/getzep/graphiti",
    license: "Apache-2.0",
  },
  {
    id: "voice-interview",
    image: "/projects/voice-interview.svg",
    imageLabel: "Concept illustration · Planned",
    imageAlt: "Concept artwork for the planned Voice Interview application.",
    title: "Voice Interview",
    subtitle: "A conversation worth practising.",
    stack: "Python · LiveKit Agents · Real-time audio",
    description:
      "A planned voice interview simulator using LiveKit, with role-specific conversations and transcript-linked feedback.",
    points: [
      "Generate follow-up questions from a role and supplied CV.",
      "Support English and German practice sessions.",
      "Review transcript feedback and response latency.",
    ],
    status: "planned",
    upstream: "LiveKit Agents",
    upstreamUrl: "https://github.com/livekit-examples/agent-starter-python",
    license: "Python starter: MIT; agent framework: Apache-2.0.",
  },
  {
    id: "evidence-notebook",
    image: "/projects/evidence-notebook.svg",
    imageLabel: "Concept illustration · Planned",
    imageAlt: "Concept artwork for the planned Evidence Notebook application.",
    title: "Evidence Notebook",
    subtitle: "Follow the claim to its source.",
    stack: "Python · Open Notebook · Retrieval evaluation",
    description:
      "A planned extension of Open Notebook for comparing research papers and technical proposals through their evidence.",
    points: [
      "Compare supporting passages side by side.",
      "Highlight conflicting claims and precise citations.",
      "Measure retrieval quality against a repeatable evaluation set.",
    ],
    status: "planned",
    upstream: "Open Notebook",
    upstreamUrl: "https://github.com/lfnovo/open-notebook",
    license: "MIT",
  },
  {
    id: "research-analyst",
    image: "/projects/research-analyst.svg",
    imageLabel: "Concept illustration · Planned",
    imageAlt: "Concept artwork for the planned Research Analyst application.",
    title: "Research Analyst",
    subtitle: "Research you can retrace.",
    stack: "Python · DeerFlow · LangGraph",
    description:
      "A planned specialised research application built on DeerFlow, focused on evidence-backed engineering comparisons.",
    points: [
      "Verify claims and surface contradictory sources.",
      "Track research budgets and recover interrupted jobs.",
      "Evaluate report quality with traceable evidence.",
    ],
    status: "planned",
    upstream: "DeerFlow",
    upstreamUrl: "https://github.com/bytedance/deer-flow",
    license: "MIT",
  },
  {
    id: "document-workflows",
    image: "/projects/document-workflows.svg",
    imageLabel: "Concept illustration · Planned",
    imageAlt: "Concept artwork for the planned Document Workflows application.",
    title: "Document Workflows",
    subtitle: "Every job, accounted for.",
    stack: "Python · Hatchet · PostgreSQL",
    description:
      "A planned document-processing application built on Hatchet’s durable workflow engine.",
    points: [
      "Process batches through extraction, classification, and indexing.",
      "Expose job history, cancellation, and duplicate handling.",
      "Demonstrate recovery from worker failures and measure throughput.",
    ],
    status: "planned",
    upstream: "Hatchet",
    upstreamUrl: "https://github.com/hatchet-dev/hatchet",
    license: "MIT",
  },
  {
    id: "workflow-studio",
    image: "/projects/workflow-studio.svg",
    imageLabel: "Concept illustration · Planned",
    imageAlt: "Concept artwork for the planned Workflow Studio application.",
    title: "Workflow Studio",
    subtitle: "Connect ideas. Inspect every step.",
    stack: "TypeScript · Next.js · Sim · PostgreSQL",
    description:
      "A planned document-operations studio extending Sim’s visual workflow builder.",
    points: [
      "Add specialised extraction, validation, and review blocks.",
      "Compare workflow versions against the same sample inputs.",
      "Build a testing interface for inspecting step outputs.",
    ],
    status: "planned",
    upstream: "Sim",
    upstreamUrl: "https://github.com/simstudioai/sim",
    license: "Apache-2.0 core; enterprise code has separate restrictions.",
  },
];
