export const projects = [
  {
    id: "agent-pipeline",
    image: "/projects/agent-pipeline.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of coordinated retrieval, planning, tools, and verification agents.",
    title: "Multi-agent pipeline",
    subtitle: "Agents with a plan. And a fallback.",
    stack: "Python · LangGraph · Structured outputs",
    description:
      "A state-driven workflow for retrieval, planning, tool selection, static analysis, and verification.",
    points: [
      "Explicit error states and retries.",
      "Human-in-the-loop checkpoints.",
      "Structured output validation.",
    ],
  },
  {
    id: "rag-platform",
    image: "/projects/rag-platform.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of documents being matched through vector and keyword retrieval.",
    title: "RAG platform",
    subtitle: "Knowledge, within reach.",
    stack: "PGVector · BM25 · Cohere · Python",
    description:
      "An end-to-end retrieval platform combining vector similarity, lexical search, and reranking.",
    points: [
      "Tuned chunking and embeddings.",
      "Hybrid BM25 + embedding search.",
      "Cohere reranking and metadata routing.",
    ],
  },
  {
    id: "model-evals",
    image: "/projects/model-evals.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of comparing model outputs through an evaluation lens.",
    title: "Fine-tuning & evals",
    subtitle: "Better models. Measured.",
    stack: "Python · OpenAI · Gemini · Evals",
    description:
      "Domain-specific classification and summarization, paired with model evaluation.",
    points: [
      "Supervised fine-tuning.",
      "Accuracy and hallucination comparisons.",
      "Cost trade-offs across models.",
    ],
  },
  {
    id: "analysis-agent",
    image: "/projects/analysis-agent.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of code review with performance and compatibility checkpoints.",
    title: "Static analysis agent",
    subtitle: "A second set of engineering eyes.",
    stack: "LLM agents · API contracts · Static analysis",
    description:
      "An engineering review agent for performance, concurrency, and compatibility risks.",
    points: [
      "N+1 queries and caching inefficiencies.",
      "Schema drift and unsafe API contracts.",
      "Missing idempotency and concurrency risks.",
    ],
  },
  {
    id: "pricing-engine",
    image: "/projects/pricing-engine.svg",
    imageLabel: "Concept illustration",
    imageAlt:
      "Concept illustration of pricing inference, caching, and request processing.",
    title: "ML pricing engine",
    subtitle: "Real-time decisions, at scale.",
    stack: "Python · Redis · DynamoDB · Autoscaling",
    description:
      "A high-throughput pricing system processing 500,000+ requests each day.",
    points: [
      "Python-based ML inference.",
      "Redis caching and DynamoDB state.",
      "Autoscaling for changing demand.",
    ],
  },
  {
    id: "project-memory",
    image: "/projects/project-memory.svg",
    imageLabel: "Concept illustration · Open source",
    imageAlt: "Concept illustration representing Graphiti.",
    title: "Graphiti",
    subtitle: "Temporal memory for AI agents.",
    stack: "Python · Graphiti · Graph databases",
    description:
      "A framework for building knowledge graphs that track changing facts, their sources, and historical validity.",
    points: [
      "Incremental ingestion of structured and unstructured information.",
      "Temporal fact tracking and historical queries.",
      "Hybrid semantic, keyword, and graph retrieval.",
    ],
    status: "open-source",
    upstream: "Graphiti",
    upstreamUrl: "https://github.com/getzep/graphiti",
    license: "Apache-2.0",
    creator: "Zep",
  },
  {
    id: "voice-interview",
    image: "/projects/voice-interview.svg",
    imageLabel: "Concept illustration · Open source",
    imageAlt: "Concept illustration representing LiveKit Agents.",
    title: "LiveKit Agents",
    subtitle: "Real-time conversations, powered by agents.",
    stack: "Python · LiveKit Agents · Real-time audio",
    description:
      "A real-time voice agent framework with a Python starter for building conversational applications.",
    points: [
      "Speech-to-text, language model, and text-to-speech integration.",
      "Turn detection and interruption handling.",
      "Evaluation examples and a companion frontend starter.",
    ],
    status: "open-source",
    upstream: "LiveKit Agents",
    upstreamUrl: "https://github.com/livekit-examples/agent-starter-python",
    license: "Python starter: MIT; agent framework: Apache-2.0.",
    creator: "LiveKit",
  },
  {
    id: "evidence-notebook",
    image: "/projects/evidence-notebook.svg",
    imageLabel: "Concept illustration · Open source",
    imageAlt: "Concept illustration representing Open Notebook.",
    title: "Open Notebook",
    subtitle: "A workspace for your sources.",
    stack: "Python · Open Notebook · Retrieval",
    description:
      "An open-source research workspace for exploring documents, web content, audio, and video with AI.",
    points: [
      "Source-based chat with full-text and vector search.",
      "Multiple model providers and local model options.",
      "Multi-speaker podcast generation and a REST API.",
    ],
    status: "open-source",
    upstream: "Open Notebook",
    upstreamUrl: "https://github.com/lfnovo/open-notebook",
    license: "MIT",
    creator: "lfnovo and contributors",
  },
  {
    id: "research-analyst",
    image: "/projects/research-analyst.svg",
    imageLabel: "Concept illustration · Open source",
    imageAlt: "Concept illustration representing DeerFlow.",
    title: "DeerFlow",
    subtitle: "A runtime for longer tasks.",
    stack: "Python · DeerFlow · LangGraph",
    description:
      "An agent runtime that coordinates multi-step work using subagents, persistent memory, tools, and sandboxed execution.",
    points: [
      "Subagents for delegated tasks and coordination.",
      "Persistent memory and filesystem access.",
      "Extensible skills, tools, and MCP integrations.",
    ],
    status: "open-source",
    upstream: "DeerFlow",
    upstreamUrl: "https://github.com/bytedance/deer-flow",
    license: "MIT",
    creator: "ByteDance and contributors",
  },
  {
    id: "document-workflows",
    image: "/projects/document-workflows.svg",
    imageLabel: "Concept illustration · Open source",
    imageAlt: "Concept illustration representing Hatchet.",
    title: "Hatchet",
    subtitle: "Durable workflows. Observable execution.",
    stack: "Python · TypeScript · Go · PostgreSQL",
    description:
      "A task orchestration platform backed by PostgreSQL for reliable background jobs and durable workflows.",
    points: [
      "Task queues, retries, and scheduled workflows.",
      "Durable waits and resumable execution.",
      "Workflow monitoring and execution observability.",
    ],
    status: "open-source",
    upstream: "Hatchet",
    upstreamUrl: "https://github.com/hatchet-dev/hatchet",
    license: "MIT",
    creator: "Hatchet and contributors",
  },
  {
    id: "workflow-studio",
    image: "/projects/workflow-studio.svg",
    imageLabel: "Concept illustration · Open source",
    imageAlt: "Concept illustration representing Sim.",
    title: "Sim",
    subtitle: "Build agents. Connect workflows.",
    stack: "TypeScript · Next.js · PostgreSQL",
    description:
      "A visual workspace for building, deploying, and monitoring AI agents and workflows.",
    points: [
      "Visual workflow composition and integrations.",
      "Collaborative workflow development and monitoring.",
      "Self-hosting and local model support.",
    ],
    status: "open-source",
    upstream: "Sim",
    upstreamUrl: "https://github.com/simstudioai/sim",
    license: "Apache-2.0 core; enterprise code has separate restrictions.",
    creator: "Sim Studio and contributors",
  },
];
